version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: game-of-life-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    
  seq:
    container_name: game-of-life-seq
    image: datalust/seq:latest
    hostname: localhost
    ports: 
        - 5341:80
    networks:
        - game-of-life-net
    environment:
        - ACCEPT_EULA=Y

volumes:
  redis_data:

networks:
  game-of-life-net:
    driver: bridge
