name: Integration Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Wait for Redis to be Ready
      run: |
        for i in {1..10}; do
          if nc -z localhost 6379; then
            echo "Redis is ready!"
            exit 0
          fi
          echo "Waiting for Redis..."
          sleep 2
        done
        echo "Redis failed to start"
        exit 1

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --configuration Release --no-restore

    - name: Run Integration Tests
      env:
        DOTNET_EnablePreviewFeatures: "true"
        Testcontainers_DisableChecks: "true"
      run: dotnet test --configuration Release --no-restore --verbosity normal --filter "Category=Integration"
