name: Performance Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  performance-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 5s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build API
      run: dotnet build ./src/GameOfLife.API/GameOfLife.API.csproj --configuration Release

    - name: Start API in Background
      run: |
        dotnet run --configuration Release --no-launch-profile --project ./src/GameOfLife.API/GameOfLife.API.csproj --urls "http://localhost:5000" &
        sleep 10
      env:
        Redis__Host: redis

    - name: Verify API is Running
      run: |
        for i in {1..10}; do
          if curl --silent --fail http://localhost:5000/health; then
            echo "API is running on http://localhost:5000"
            exit 0
          fi
          echo "Waiting for API to be ready..."
          sleep 2
        done
        echo "API failed to start"
        exit 1

    - name: Install K6
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common
        curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run Performance Test
      run: k6 run ./src/GameOfLife.Tests/Performance/performance-test.js
      env:
        API_URL: http://localhost:5000
