name: Performance Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  performance-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Docker BuildKit
      run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

    - name: List Running Docker Containers
      run: docker ps -a

    - name: Wait for Redis to Be Ready
      run: |
        for i in {1..10}; do
          if docker exec redis redis-cli ping | grep -q PONG; then
            echo "Redis is ready."
            exit 0
          fi
          echo "Waiting for Redis to be ready..."
          sleep 2
        done
        echo "Redis failed to start."
        exit 1

    - name: Change to Docker Directory and Build API Image
      run: |
        cd docker
        docker build -t gameoflife-api:latest -f ../src/GameOfLife.API/Dockerfile ../

    - name: Start API Container
      run: |
        docker run -d --name gameoflife-api -p 80:80 -p 443:443 --env Redis__Host=redis gameoflife-api:latest
        sleep 10
        
    - name: Display API Logs
      run: docker logs gameoflife-api

    - name: Verify API is Running
      run: |
        for i in {1..15}; do
          if curl --silent --fail http://localhost:80/health; then
            echo "API is running on http://localhost:80"
            exit 0
          fi
          echo "Waiting for API to be ready..."
          sleep 5
        done
        echo "API failed to start"
        exit 1

    - name: Install K6
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common
        curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run Performance Test
      run: k6 run ./src/GameOfLife.Tests/Performance/performance-test.js
      env:
        API_URL: http://localhost:80

    - name: Cleanup Containers
      run: docker stop gameoflife-api && docker rm gameoflife-api
